### ISSUE TITLE
Add global response handlers

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-rest#13]
Now we can define Global response handlers, the handler can handle both success and failed responses, and the handler will be called *before* the the specific request handlers are called.

Use :

- Define the handler

```
import org.dominokit.domino.rest.shared.request.FailedResponseBean;
import org.dominokit.domino.rest.shared.request.GlobalResponseHandler;
import org.dominokit.domino.rest.shared.request.ServerRequest;

public class SampleGlobalResponseHnadler implements GlobalResponseHandler {

    @Override
    public void interceptOnSuccess(ServerRequest serverRequest, String body) {
        //do something with the success response.
    }

    @Override
    public void interceptOnFailed(ServerRequest serverRequest, FailedResponseBean failedResponse) {
        //do something with the failed response.
    }
}
```
- Add the handler

```
DominoRestConfig.getInstance().addGlobalResponseHandler(new SampleGlobalResponseHnadler());
```
both methods of the GlobalResponseHandler are default to do nothing.

**Comment by TDesjardins** [comment]
I like the option to have more control about responses with the global response handler feature. I wonder why the API design differs between request and responses. For the requests there is an interceptor which implements an interface. For the responses a response handler is used. It feels a little bit inconsequent or is this a result of technical restrictions?

**Comment by vegegoku** [comment]
Thank you @TDesjardins for the question, Request interceptors plays a different role, the idea behind the request interceptor is to block sending the request until all interceptors are execute, this is useful for cases where you need to add some general headers or authentication headers, or enrich the request with some data, or even sometimes to define a global retry and timeout rules. and in all of these cases you normally would want to block the request and delay the sending process.

Now for responses there should be no need to globally block handling the response, this is mainly to handle general errors, or to do some logging. 

so they serve different use cases, and notice that in case of response you also have a success case and failure case but in the request you dont have such things.

I will be glad to hear any more about this, i would love to improve it if possible in a sensible way.
