### ISSUE TITLE
Generate factory methods for service methods from super interfaces

### ISSUE THREAD

**Issue by vegegoku** [DominoKit/domino-rest#14]
This allows inheritance of service methods from super interfaces, so now a service interface can extend from multiple other interfaces that define rest methods.

the `@RequestFactory` or `@Path` annotations will only be processed from the root interface.

**Comment by masterdany88** [comment]
So I can declare jaxrs interfaces to be used by client generators and also use it on backend without @RequestFactory annotation and any domino dependency?
