### ISSUE TITLE
User JAXRS standard @ApplicationPath instead of @RequestFactory

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-rest#15]
Why use `@RequestFactory(serviceRoot = "http://localhost:7070/")` when JAXRS has its way/standard of doing this, which is `@ApplicationPath`, `javax.ws.rs.ApplicationPath`, more details here: 

- https://docs.oracle.com/javaee/7/api/javax/ws/rs/ApplicationPath.html
- https://www.logicbig.com/tutorials/java-ee-tutorial/jax-rs/path-annotion-resource-mapping.html
- https://tomee.apache.org/examples-trunk/rest-example-with-application/

F.e.:
```

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("/rest_root")
public class ApplicationConfig extends Application {
}
```
or
```

import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

@ApplicationPath("https://www.google.com/api/v3")
public class ApplicationConfig extends Application {
}
```

**Comment by vegegoku** [comment]
@TDesjardins @FrankHossfeld i would love to have you both in the discussion for this issue.

**Comment by TDesjardins** [comment]
I would prefer @ApplicationPath over @RequestFactory.
I currently use only relative paths so the @RequestFactory annotation is just a marker:

```
@RequestFactory
@Path("info")
public interface InfoServiceClient {
```

**Comment by FrankHossfeld** [comment]
I have no destinct position. But think, the current implementation is ok. 

Looking at the docs of `ApplicationPath`, it says: 
> Identifies the application path that serves as the base URI for all resource URIs provided by Path. May only be applied to a subclass of Application.

So, the service interface does not extends Application. 

Looking at the Errai services, they also use `@Path` for services:
```java
@Path("customers")
public interface CustomerService {

  @GET
  @Produces("application/json")
  public List<Customer> listAllCustomers();


  @POST
  @Consumes("application/json")
  @Produces("text/plain")
  public long createCustomer(Customer customer);

}
```
Correct me, If i am wrong, but I think, the `@RequestFactory`-annotation triggers the processor. Of course, the processor can be triggered with `@ApplicationPath`, but then, it does something different.

**Comment by masterdany88** [comment]
@ApplicationPath for root path is standard in jaxrs.

**Comment by vegegoku** [comment]
@masterdany88 would you please add a comment for closing this issue?

**Comment by masterdany88** [comment]
Current solution is much better with package-info.java and @ResourceList
