### ISSUE TITLE
NPE for Map-Params in method body on POST-Requests

### ISSUE THREAD

**Issue by mamta** [DominoKit/domino-rest#21]
Hi, I tried to post with Map-param and getting NPE, Is map not supported for method body on POST-Requests?

@POST
@Path(PathConstants.APP_REGISTER_USER_REQUEST)
@Produces(MediaType.APPLICATION_JSON)
Void registerUser(@RequestBody HashMap<String, String> personalData);

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.0:compile (default-compile) on project ip-client: Compilation failure
[ERROR] error while creating source file java.lang.NullPointerException
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.isRequestBody(RequestFactorySourceWriter.java:270)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.isBodyParameter(RequestFactorySourceWriter.java:254)
[ERROR]       at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
[ERROR]       at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1812)
[ERROR]       at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
[ERROR]       at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
[ERROR]       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
[ERROR]       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[ERROR]       at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
[ERROR]       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]       at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:531)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.getRequestBeanType(RequestFactorySourceWriter.java:236)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.makeRequestClass(RequestFactorySourceWriter.java:169)
[ERROR]       at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
[ERROR]       at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
[ERROR]       at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
[ERROR]       at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
[ERROR]       at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
[ERROR]       at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
[ERROR]       at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactorySourceWriter.asTypeBuilder(RequestFactorySourceWriter.java:65)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactoryProcessingStep.generateFactory(RequestFactoryProcessingStep.java:55)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactoryProcessingStep.process(RequestFactoryProcessingStep.java:46)
[ERROR]       at org.dominokit.domino.rest.apt.RequestFactoryProcessor.process(RequestFactoryProcessor.java:42)
[ERROR]       at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor(JavacProcessingEnvironment.java:802)
[ERROR]       at com.sun.tools.javac.processing.JavacProcessingEnvironment.discoverAndRunProcs(JavacProcessingEnvironment.java:713)
[ERROR]       at com.sun.tools.javac.processing.JavacProcessingEnvironment.access$1800(JavacProcessingEnvironment.java:91)
[ERROR]       at com.sun.tools.javac.processing.JavacProcessingEnvironment$Round.run(JavacProcessingEnvironment.java:1043)
[ERROR]       at com.sun.tools.javac.processing.JavacProcessingEnvironment.doProcessing(JavacProcessingEnvironment.java:1184)
[ERROR]       at com.sun.tools.javac.main.JavaCompiler.processAnnotations(JavaCompiler.java:1170)
[ERROR]       at com.sun.tools.javac.main.JavaCompiler.compile(JavaCompiler.java:856)
[ERROR]       at com.sun.tools.javac.main.Main.compile(Main.java:523)
[ERROR]       at com.sun.tools.javac.api.JavacTaskImpl.doCall(JavacTaskImpl.java:129)
[ERROR]       at com.sun.tools.javac.api.JavacTaskImpl.call(JavacTaskImpl.java:138)
[ERROR]       at org.codehaus.plexus.compiler.javac.JavaxToolsCompiler.compileInProcess(JavaxToolsCompiler.java:126)
[ERROR]       at org.codehaus.plexus.compiler.javac.JavacCompiler.performCompile(JavacCompiler.java:174)
[ERROR]       at org.apache.maven.plugin.compiler.AbstractCompilerMojo.execute(AbstractCompilerMojo.java:1129)
[ERROR]       at org.apache.maven.plugin.compiler.CompilerMojo.execute(CompilerMojo.java:188)
[ERROR]       at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
[ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
[ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
[ERROR]       at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
[ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
[ERROR]       at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
[ERROR]       at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
[ERROR]       at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
[ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
[ERROR]       at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
[ERROR]       at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
[ERROR]       at org.apache.maven.cli.MavenCli.execute(MavenCli.java:956)
[ERROR]       at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
[ERROR]       at org.apache.maven.cli.MavenCli.main(MavenCli.java:192)
[ERROR]       at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[ERROR]       at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[ERROR]       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[ERROR]       at java.lang.reflect.Method.invoke(Method.java:498)
[ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
[ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
[ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
[ERROR]       at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)
[ERROR] -> [Help 1]

Thanks and regards

**Comment by vegegoku** [comment]
Yes it is not supported yet, i will add support for all types just like how we support the return type, thank you for reporting

**Comment by vegegoku** [comment]
after some thinking this will break something, normally with the request body when you use an object then you can replace path and query parameter using fields from the request object, but since the request object could also any type in its fields including map, then i am still going to support this, but will leave it to the compiler to let you know if you are doing something wrong.

another thing is that it is also possible to work around this using a writer.

**Comment by vegegoku** [comment]
after checking the code, the RequestBody is supported for most of the types including primitives, arrays, collections, enums, and iterable, the map missing.

**Comment by vegegoku** [comment]
This fix lead to another issue related to how the serializer is being generated which does not match how domino-jackson handles this case. so i will reopen the issue to push the new fix.

**Comment by vegegoku** [comment]
the issue from above will make the following fails to compile with GWT compiler 
```java
public class CommonsLabelsService_registerUser extends ServerRequest<Map<String, String>, Void> {
    CommonsLabelsService_registerUser(Map<String, String> request) {
        super(request);
        setHttpMethod("POST");
        setContentType(new String[]{"application/json"});
        setAccept(new String[]{"application/json"});
        setPath("/commons/localization");
        setServiceRoot("");
        setRequestWriter(bean -> new AbstractObjectWriter<Map<String, String>>("java.util.Map<java.lang.String,java.lang.String>") {
            @Override
            protected JsonSerializer<Map<String, String>> newSerializer() {
                return MapJsonSerializer.newInstance(ToStringKeySerializer.getInstance(), StringJsonSerializer.getInstance());
            }
        }.write(bean));
        setRequestParametersReplacer((token, bean) -> {
            if (token.hasVariables()) {
            }
            return token.value();
        });
    }
}
```

and the error

```
[INFO] Compiling module com.progressoft.alpha.AppClientModule
[INFO]    Tracing compile failure path for type 'com.progressoft.alpha.commons.shared.service.CommonsLabelsService_registerUser'
[INFO]       [ERROR] Errors in 'jar:file:/mnt/CODE/GIT/PROGRESSOFT/PAYMENT-HUB/payhub/commons/commons-shared/target/commons-shared-1.0-SNAPSHOT-sources.jar!/com/progressoft/alpha/commons/shared/service/CommonsLabelsService_registerUser.java'
[INFO]          [ERROR] Line 25: Type mismatch: cannot convert from MapJsonSerializer<Map<?,?>,capture#1-of ?,capture#2-of ?> to JsonSerializer<Map<String,String>>
[INFO]    [ERROR] Aborting compile due to errors in some input files
```

the fix is to change the `JsonSerializer<Map<String,String>>` to `JsonSerializer<?>`
