### ISSUE TITLE
Add support for multipart POST

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-rest#44]
With a part containing JSON, and other part(s) containing binary data like images for example.

**Comment by rjeeb** [comment]
@FrankW76 We implemented the first draft of this feature and your testing and feedback is much appreciated.

For defining a multipart form data request, please find the [documentation](https://github.com/DominoKit/domino-rest/wiki/Multipart-form-data).

These changes will be found in the latest `HEAD-SNAPSHOT` dependency.
