### ISSUE TITLE
Add support to set XmlHttpRequest withCredentials

### ISSUE THREAD

**Issue by FrankW76** [DominoKit/domino-rest#51]
See https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#Properties

In my case I need to set the withCredentials property to true.
When using elemental2 XmlHttpRequest this can be achieved by

```
XMLHttpRequest xhr = new XMLHttpRequest();
xhr.withCredentials = true;
```

With domino-rest it seems that you don't have access to these properties.

Please provide something so we can set these properties using domino-rest.

**Comment by FrankW76** [comment]
I noted that domino-rest uses org.gwtproject.xhr.client.XMLHttpRequest and not elemental2.

With org.gwtproject.xhr.client.XMLHttpRequest you can set withCredentials using

`xmlHttpRrequest.setWithCredentials(true);`

**Comment by FrankW76** [comment]
I added request.setWithCredentials(true) to JsRestFulRequest.java to test if this would work

```
public JsRestfulRequest(String uri, String method) {
     super(uri, method);
     request = XMLHttpRequest.create();
     request.setWithCredentials(true);
     parseUri(uri);
}
```

And can confirm that now my software works.
So if something can be provided in domino-rest too set the value of this withCredentials parameter that would fix my problem.

**Comment by vegegoku** [comment]
the `withCredentials` is the only missing one
