### ISSUE TITLE
Additional handler method declaration at the end of rest request no matter if it was successful or not

### ISSUE THREAD

**Issue by masterdany88** [DominoKit/domino-rest#54]
Please add additional method like `onBeforeSend`, but for the end of request, f.e.: `onAfterSend` or `onFinish` to be used like:
```
UpdaterRestResourceFactory.INSTANCE
                .getStatus()
                .onBeforeSend(() -> uiLocker.start())
                .onSuccess(this::onGetSuccess)
                .onFail(f->onFailed())
                .onAfterSend(() -> uiLocker.stop())
                .send();
```

F.e. When I call any rest endpoint on the backend I block ui using Animation with help of method `onBeforeSend()`, then after requests end I need to unblock the ui stopping animation. To do that I currently both handlers: `onSuccess` and `onFail`.
So in `onFail` method I do not handle failed event, but I am just stoping the animation, and because of that default handler is not triggered (`DominoRestConfig.getInstance().setDefaultFailHandler`)

**Comment by vegegoku** [comment]
https://github.com/DominoKit/domino-rest/issues/48
