### ISSUE TITLE
Please publish non-snapshot versions for use by those of us who aren't allowed to use snapshot servers.

### ISSUE THREAD

**Issue by michael-newsrx** [DominoKit/domino-rest#55]
Please publish non-snapshot versions for use by those of us who aren't allowed to use snapshot servers.

(The last version I can find on maven central is october 2019).

**Comment by FrankHossfeld** [comment]
The problem is, that some of the dependencies aren't deployed to Maven Central. So, domino-rest has to wait until they are deployed.

**Comment by mdavis95** [comment]
Is it possible to release a version now that 1.0.0-RC1 versions are in maven central?

**Comment by vegegoku** [comment]
> Is it possible to release a version now that 1.0.0-RC1 versions are in maven central?

We are already working on that, one lib at a time. we have a lot of work for each, like adding java-doc, and testing for both gwt and j2cl, updating dependencies..etc but we are working on it.

**Comment by mdavis95** [comment]
Great news!

**Comment by vegegoku** [comment]
1.0.0-beta2 is now in maven central

**Comment by vegegoku** [comment]
domino-rest 1.0.0-RC1 is now in maven central
