### ISSUE TITLE
Mangled generated file when using Eclipse

### ISSUE THREAD

**Issue by michael-conrad** [DominoKit/domino-rest#61]
I have a simple interface setup for "login/logout" as a starting point, but the apt processor is generating mangled output when auto run from Eclipse. The output generated during a Gradle build appears fine.

The import "import org.dominokit.jacksonapt.deser.StringJsonDeserializer;" is being mangled to "import package java.lang.StringBeanJsonDeserializerImpl;"

The full project is available at: [Github project: AudioQualityVote](https://github.com/CherokeeLanguage/AudioQualityVote)

This pretty much renders the apt processor useless when used in Eclipse.

## Eclipse generated file:

```Java
package com.cherokeelessons.audio.quality.shared;

import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import javax.annotation.Generated;
import org.dominokit.domino.rest.shared.request.RequestMeta;
import org.dominokit.domino.rest.shared.request.ServerRequest;
import org.dominokit.domino.rest.shared.request.service.annotations.Request;
import org.dominokit.domino.rest.shared.request.service.annotations.RestService;
import org.dominokit.jacksonapt.AbstractObjectReader;
import org.dominokit.jacksonapt.JsonDeserializer;
import package java.lang.StringBeanJsonDeserializerImpl;
```
## Gradle generated file:

```Java
package com.cherokeelessons.audio.quality.shared;

import java.lang.Override;
import java.lang.String;
import java.lang.Void;
import javax.annotation.Generated;
import org.dominokit.domino.rest.shared.request.RequestMeta;
import org.dominokit.domino.rest.shared.request.ServerRequest;
import org.dominokit.domino.rest.shared.request.service.annotations.Request;
import org.dominokit.domino.rest.shared.request.service.annotations.RestService;
import org.dominokit.jacksonapt.AbstractObjectReader;
import org.dominokit.jacksonapt.JsonDeserializer;
import org.dominokit.jacksonapt.deser.StringJsonDeserializer;
```

**Comment by vegegoku** [comment]
Not only the issue is with `package` being added, but notice that it is generating a custom Deserializer for the `String` class while it should use the built-in one just like the gradle one.

**Comment by michael-conrad** [comment]
yeah... seems other constructs cause it to puke:

```Java
@JSONMapper
public class KeyValueResponse extends HashMap<String, String> {
}
```

results in (Gradle build fail):

```Java
BUILD SUCCESSFUL in 1s
6 actionable tasks: 6 executed
muksihs@Precision-Workstation:~/git/AudioQualityVote$ gradle build

> Task :audio-quality-vote-shared:compileJava FAILED
/home/muksihs/git/AudioQualityVote/audio-quality-vote-shared/build/generated/sources/annotationProcessor/java/main/java/util/HashMap_Node_String_StringBeanJsonDeserializerImpl.java:1: error: package exists in another module: java.base
package java.util;
^
/home/muksihs/git/AudioQualityVote/audio-quality-vote-shared/build/generated/sources/annotationProcessor/java/main/java/util/Map_Entry_String_StringBeanJsonDeserializerImpl.java:1: error: package exists in another module: java.base
package java.util;

```

**Comment by vegegoku** [comment]
how do you build? and do we need a plugin for eclipse to work with annotation processors? 
I only use intellij.

**Comment by michael-conrad** [comment]
Final production builds will be done via Gradle.

To have apt processors work in Eclipse when specified via Gradle requires a Gradle plugin in combination with running 3 Gradle tasks. Plugin: "com.diffplug.eclipse.apt".

See the file [eclipseFixApt.sh](https://github.com/CherokeeLanguage/AudioQualityVote/blob/main/eclipseFixApt.sh) for the Gradle tasks needed.

**Comment by michael-conrad** [comment]
Just figured out that if I set the return type to void, no errors are generated.

If I set the return type to a @JSONMapper annotated POJO, it does the same as if with String, so that's apparently not a viable work around. And then I start getting messages about modules and things showing up in multiple places... even though this isn't a module oriented project.

**Comment by vegegoku** [comment]
I meant how you build with eclipse, for gradle i can just do `gradle build` ..right, since this works in intellij from both ide and gradle.

Now i wonder how you force eclipse to build this project and generate the sources.?!

**Comment by vegegoku** [comment]
in eclipse when i  do build project it does nothing at all.

**Comment by michael-conrad** [comment]
Ah... sorry.

I would use the Gradle import function for the parent project - which will pull in the child projects automatically.

I would then run ./eclipseAptFix.sh

I would then refresh the afflicted project by pressing "F5" when it is selected. Project: Audio Quality Vote (Shared)

Then probably a clean all and let Eclipse auto build everything.

**Comment by michael-conrad** [comment]
I've created a branch with the error. I would have liked to use the newer rest stuff, but, as it isn't working in my Eclipse.... [domino-rest branch](https://github.com/CherokeeLanguage/AudioQualityVote/tree/domino-rest)

**Comment by vegegoku** [comment]
> Ah... sorry.
> 
> I would use the Gradle import function for the parent project - which will pull in the child projects automatically.
> 
> I would then run ./eclipseAptFix.sh
> 
> I would then refresh the afflicted project by pressing "F5" when it is selected. Project: Audio Quality Vote (Shared)
> 
> Then probably a clean all and let Eclipse auto build everything.

I did all of this and eclipse still does not even try to do anything, I even tried to turn off the automatic build and do build all, but still it does nothing at all.

**Comment by michael-conrad** [comment]
a) I presume all projects were created in Eclipse correctly when imported via buildship.

b) There should be an ".apt_generated" folder in "AudioQualityVote/audio-quality-vote-shared", along with a .factory file and two "*.jdt*" files in the folder .settings/

For comparison:

```bash
tree -a audio-quality-vote-shared/
audio-quality-vote-shared/
├── .apt_generated
│   └── com
│       └── cherokeelessons
│           └── audio
│               └── quality
│                   └── shared
│                       └── RestApiFactory.java
├── .apt_generated_tests
├── bin
│   ├── default
│   │   └── com
│   │       └── cherokeelessons
│   │           └── audio
│   │               └── quality
│   │                   └── shared
│   │                       ├── RestApiFactory$RestApi_login.class
│   │                       ├── RestApiFactory$RestApi_logout.class
│   │                       └── RestApiFactory.class
│   ├── main
│   │   ├── com
│   │   │   └── cherokeelessons
│   │   │       └── audio
│   │   │           └── quality
│   │   │               └── shared
│   │   │                   ├── AudioQualityVoteShared.gwt.xml
│   │   │                   └── RestApi.class
│   │   └── .gitignore
│   └── test
│       └── .gitignore
├── build.gradle
├── .classpath
├── .factorypath
├── .gitignore
├── .project
├── .settings
│   ├── org.eclipse.buildship.core.prefs
│   ├── org.eclipse.core.resources.prefs
│   ├── org.eclipse.core.runtime.prefs
│   ├── org.eclipse.jdt.apt.core.prefs
│   ├── org.eclipse.jdt.core.prefs
│   ├── org.eclipse.wst.common.component
│   └── org.eclipse.wst.common.project.facet.core.xml
└── src
    ├── main
    │   ├── java
    │   │   ├── com
    │   │   │   └── cherokeelessons
    │   │   │       └── audio
    │   │   │           └── quality
    │   │   │               └── shared
    │   │   │                   └── RestApi.java
    │   │   └── .gitignore
    │   └── resources
    │       ├── com
    │       │   └── cherokeelessons
    │       │       └── audio
    │       │           └── quality
    │       │               └── shared
    │       │                   └── AudioQualityVoteShared.gwt.xml
    │       └── .gitignore
    └── test
        ├── java
        │   └── .gitignore
        └── resources
            └── .gitignore

39 directories, 26 files
```

**Comment by vegegoku** [comment]
I managed to reproduce in a simple maven project with eclipse

**Comment by vegegoku** [comment]
I found the cause of the issue and have the fix for it, the issue source is domino-jackson, as there is code that tries to get the package name and convert it without calling getQualifiedName first. this will be fixed in domino-jackson and we will deploy a new domino-rest snapshot

**Comment by vegegoku** [comment]
@michael-conrad can you please confirm the issue is fixed for you after updating to the new snapshot?

**Comment by vegegoku** [comment]
> yeah... seems other constructs cause it to puke:
> 
> ```java
> @JSONMapper
> public class KeyValueResponse extends HashMap<String, String> {
> }
> ```
> 
> results in (Gradle build fail):
> 
> ```java
> BUILD SUCCESSFUL in 1s
> 6 actionable tasks: 6 executed
> muksihs@Precision-Workstation:~/git/AudioQualityVote$ gradle build
> 
> > Task :audio-quality-vote-shared:compileJava FAILED
> /home/muksihs/git/AudioQualityVote/audio-quality-vote-shared/build/generated/sources/annotationProcessor/java/main/java/util/HashMap_Node_String_StringBeanJsonDeserializerImpl.java:1: error: package exists in another module: java.base
> package java.util;
> ^
> /home/muksihs/git/AudioQualityVote/audio-quality-vote-shared/build/generated/sources/annotationProcessor/java/main/java/util/Map_Entry_String_StringBeanJsonDeserializerImpl.java:1: error: package exists in another module: java.base
> package java.util;
> ```

I don't expect this work, since Map isn't a pojo, supporting such use case should be submitted as a feature request to discuss the possible implementations.

**Comment by michael-conrad** [comment]
The generated source now compiles fine. So I think this can be closed.

However, now I'm getting things like the following when running a "gradle clean build":

```Java
> Task :audio-quality-vote-ui:compileGwt
Compiling module com.cherokeelessons.audio.quality.AudioQualityVote
   Tracing compile failure path for type 'org.dominokit.domino.rest.gwt.DefaultServiceRoot'
      [ERROR] Errors in 'jar:file:/home/muksihs/.gradle/caches/modules-2/files-2.1/org.dominokit/domino-rest-gwt/1.0-rc.4-SNAPSHOT/baddc0c6ba6e8e9a4725efe647ba7c3bc0f643dd/domino-rest-gwt-1.0-rc.4-SNAPSHOT.jar!/org/dominokit/domino/rest/gwt/DefaultServiceRoot.java'
         [ERROR] Line 11: The method getHost() is undefined for the type Location
         [ERROR] Line 10: The method getProtocol() is undefined for the type Location
   Tracing compile failure path for type 'org.dominokit.jacksonapt.deser.array.cast.JsStringArrayReader'
      [ERROR] Errors in 'jar:file:/home/muksihs/.gradle/caches/modules-2/files-2.1/org.dominokit.jackson/jackson-apt/1.0-SNAPSHOT/b401829221b7cbd6a948b55feccd6161e7ca0b5d/jackson-apt-1.0-SNAPSHOT.jar!/org/dominokit/jacksonapt/deser/array/cast/JsStringArrayReader.java'
         [ERROR] Line 36: Type mismatch: cannot convert from JsArray<JsString> to JsString[]
   Tracing compile failure path for type 'org.dominokit.jacksonapt.stream.impl.JsIntegerStack'

```

**Comment by vegegoku** [comment]
> The generated source now compiles fine. So I think this can be closed.
> 
> However, now I'm getting things like the following when running a "gradle clean build":
> 
> ```java
> > Task :audio-quality-vote-ui:compileGwt
> Compiling module com.cherokeelessons.audio.quality.AudioQualityVote
>    Tracing compile failure path for type 'org.dominokit.domino.rest.gwt.DefaultServiceRoot'
>       [ERROR] Errors in 'jar:file:/home/muksihs/.gradle/caches/modules-2/files-2.1/org.dominokit/domino-rest-gwt/1.0-rc.4-SNAPSHOT/baddc0c6ba6e8e9a4725efe647ba7c3bc0f643dd/domino-rest-gwt-1.0-rc.4-SNAPSHOT.jar!/org/dominokit/domino/rest/gwt/DefaultServiceRoot.java'
>          [ERROR] Line 11: The method getHost() is undefined for the type Location
>          [ERROR] Line 10: The method getProtocol() is undefined for the type Location
>    Tracing compile failure path for type 'org.dominokit.jacksonapt.deser.array.cast.JsStringArrayReader'
>       [ERROR] Errors in 'jar:file:/home/muksihs/.gradle/caches/modules-2/files-2.1/org.dominokit.jackson/jackson-apt/1.0-SNAPSHOT/b401829221b7cbd6a948b55feccd6161e7ca0b5d/jackson-apt-1.0-SNAPSHOT.jar!/org/dominokit/jacksonapt/deser/array/cast/JsStringArrayReader.java'
>          [ERROR] Line 36: Type mismatch: cannot convert from JsArray<JsString> to JsString[]
>    Tracing compile failure path for type 'org.dominokit.jacksonapt.stream.impl.JsIntegerStack'
> ```

This might be related to the fact that you are using gwt2.9 while we are still using 2.8.2 and the difference in elemental2 versions.

**Comment by michael-conrad** [comment]
> This might be related to the fact that you are using gwt2.9 while we are still using 2.8.2 and the difference in elemental2 versions.

Yeah... that has pretty much been a show stopper for trying to use domino-rest for the project. I've ended up going back to resty-gwt.

**Comment by vegegoku** [comment]
we are already working on the upgrade and we should have it done soon
