### ISSUE TITLE
Null values for query parameters should not be present in the requests

### ISSUE THREAD

**Issue by natros** [DominoKit/domino-rest#66]
Using this example

```java
@RequestFactory
@Path("/users")
@Produces("application/json")
@Consumes("application/json")
public interface UserResource {
  @GET
  List<UserDto> getUsers(@QueryParam("id") @Nullable Integer id);
}
```

When calling `UserResourceFactory.INSTANCE.getUsers(null)` the parameter `id` is present in the URI as `http://localhost/api/users?id=`

And RestEasy, the backend that I'm using, complains that cannot convert `''` to `Integer`

The [documentation](https://docs.oracle.com/cd/E19798-01/821-1841/6nmq2cp1v/index.html) states that

> If @DefaultValue is not used in conjunction with @QueryParam, and the query parameter is not present in the request, the value will be an empty collection for List, Set, or SortedSet; null for other object types; and the default for primitive types.

I'm trying to migrate a GWT project that uses RestyGWT to Domino-Rest, and RestyGWT does not include `id` query parameter when is null

The JAX-RS: Java API for RESTful Web Services is available at  https://download.oracle.com/otndocs/jcp/jaxrs-2_0-fr-eval-spec/index.html for download.

**Comment by vegegoku** [comment]
Fixed in the latest `HEAD-SNAPSHOT` and will be part of the next release.

The default behavior remains the same as the current and can be configured globally using the DominoRestConfig

```java
DominoRestConfig.initDefaults();

DominoRestConfig.getInstance().setNullQueryParamStrategy(NullQueryParamStrategy.NULL);
DominoRestConfig.getInstance().setNullQueryParamStrategy(NullQueryParamStrategy.EMPTY);
DominoRestConfig.getInstance().setNullQueryParamStrategy(NullQueryParamStrategy.OMIT);

```
`NullQueryParamStrategy.EMPTY` is the default.

The behavior can be overridden for a specific service or service method using the `NullQueryStrategy` annotation.

**Comment by natros** [comment]
Excellent work!

In my case, the `NullQueryParamStrategy.OMIT` is what I needed.

Tested with google chrome and gwt 2.9.0

Thank you.
