### ISSUE TITLE
NoClassDefFoundError: javax/ws/rs/Path in RequestFactoryProcessor

### ISSUE THREAD

**Issue by foal** [DominoKit/domino-rest#82]
I am using the [annotationProcessorPaths](https://maven.apache.org/plugins/maven-compiler-plugin/compile-mojo.html#annotationProcessorPaths) option of `maven-compiler-plugin` to enable annotation processing. 

The problem is that `domino-rest-processor` has dependency to the `domino-rest-jaxrs` with `provided` scope.

As workaround I need to add manually the `domino-rest-jaxrs` to the annotation processing CLASSPATH.

```
<plugin>                                                                          
	<artifactId>maven-compiler-plugin</artifactId>                                
	<configuration>                                                               
		<release>11</release>                                                     
		<showWarnings>true</showWarnings>                                         
		<annotationProcessorPaths>                                                
			<path>                                                                
				<groupId>org.dominokit</groupId>                                  
				<artifactId>domino-rest-processor</artifactId>                    
				<version>${domino-rest.ver}</version>                             
			</path>                                                               
			<!-- Workaround for issue https://github.com/DominoKit/domino-rest/issues/82 -->                                         
			<path>                                                                
				<groupId>org.dominokit</groupId>                                  
				<artifactId>domino-rest-jaxrs</artifactId>                        
				<version>${domino-rest.ver}</version>                             
			</path>                                                               
		</annotationProcessorPaths>                                               
	</configuration>                                                              
</plugin>                                                                         
```

**Comment by vegegoku** [comment]
`domino-rest-jaxrs` is an emulation for jax-rs is not supposed to exists in the server where you will probably will be having the original jax-rs dependencies, and since domino-rest can be used in both sides -client and server- we cant make the processor to directly depends on the emulated one, since will cause other issues, so we expect the application to provide the dependency based on where he is using the processor.

**Comment by foal** [comment]
It is true when you use the processor as general dependency for the project (simplest but generally wrong way). But in my case, I setup different classpath for annotation processing only.

**Comment by vegegoku** [comment]
> It is true when you use the processor as general dependency for the project (simplest but generally wrong way). But in my case, I setup different classpath for annotation processing only.

That does not change the fact that we cant just implicitly add the dependency and let it leak to the server for example, so the current approach is flexible in how it let you define it to fit the need or the approach.

I have seen things goes wrong

**Comment by foal** [comment]
Ok. I can say that if developer add annotation processor to the project dependencies instead of tool classpath it should think about risks add exclude to this dependency if it is necessary, but unfortunately it doesn't work that way.

So, could you at least document the workaround?

**Comment by vegegoku** [comment]
With the new release 1.0.1 there will be no need to include the `domino-rest-jaxrs` dependency as a normal project dependency or in the processor path, we have changed our approach to super sources in way that is compatible with both gwt and j2cl.
